server:
  port: "8080"
database:
  dsn: "ccit:123456@tcp(localhost:3306)/ccit?charset=utf8mb4&parseTime=True&loc=Local"
  min_connection: 10
  max_connection: 100
key:
  news_apikey: "7292bbea82b0ad89f513adaa8d4a5d93"